import pandas as pd
maria = pd.Series([800,700,1000,900,1200,600,600])
joao = pd.Series([900,500,1100,1000,900,500,700])
manuel = pd.Series([700,600,900,1200,900,700,400])

Maior_Venda = (maria.max())
print("\n---Informações sobre a Vendedora Maria---")
print(f"O total de vendas é R${maria.sum():.2f}")
print(f"A média de vendas é R${maria.mean():.2f}")
print(f"O Maior valor de vendas é R${maria.max():.2f}")
print(f"O Menor valor de vendas é R${maria.min():.2f}")
print("\n---Informações sobre o Vendedor João---")
print(f"O Total de vendas é R${joao.sum():.2f}")
print(f"A Média de vendas é R${joao.mean():.2f}")
print(f"O Maior valor de vendas é R${joao.max():.2f}")
print(f"O Menor valor de vendas é R${joao.min():.2f}")
print("\n---Informações sobre o Vendedor Manuel---")
print(f"O total de vendas é R${manuel.sum():.2f}")
print(f"A média de vendas é R${manuel.mean():.2f}")
print(f"O Maior valor de vendas é R${manuel.max():.2f}")
print(f"O Menor valor de vendas é R${manuel.min():.2f}")